language: python

python:
  - 3.7

bundler_args: --retry 3

install:
  - sudo apt-get update
  - sudo apt-get install texlive texlive-science texlive-latex-extra texlive-bibtex-extra texlive-fonts-extra
  - ./utils/travis_miniconda.sh
  - PATH="$HOME/miniconda/bin:$PATH"
  - conda env create -f environment.yml

script:
  - source .envrc
  - travis_wait run-project
  - py.test

  # We want to enforce a proper formatting of the notebooks.
  - flake8-nb; [ $? -eq 0 ] || exit 1
  - black-nb .; [ $? -eq 0 ] || exit 1

  # We also want to run selected scripts
  - cd problem-sets/01-potential-outcome-model/data; python data-generation.py
  - cd ../../03-regression-discontinuity-design/sources; python auxiliary.py

notifications:
  email:
     on_success: change
     on_failure: change
